#!/bin/bash -e

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
case `uname` in
  *CYGWIN*|*MINGW*|*MSYS*) script_dir=`cygpath -w ${script_dir}`
esac

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }

GH_ORG="$1"

[[ -n $GH_ORG ]] || die "must provide orgname"
[[ -d $GH_ORG ]] || die "Must be in parent of $GH_ORG dir"

REPO_LIST_JSON=`gh repo list "${GH_ORG}" --limit 450 --json name,diskUsage,contactLinks,id,languages,owner,parent,url`
printf "Processing %d repos\n" `echo $REPO_LIST_JSON | jq '. | length'`
REPO_LIST=`echo $REPO_LIST_JSON | jq -r '.[] .name'`

for repo in $REPO_LIST
do
  echo ""
  echo "git@github.com:${GH_ORG}/${repo}.git"
  echo "================================================================"

  if ! [[ -d "${GH_ORG}/${repo}" ]]; then
    echo git clone "git@github.com:${GH_ORG}/${repo}.git" "${GH_ORG}/${repo}"
    git clone "git@github.com:${GH_ORG}/${repo}.git" "${GH_ORG}/${repo}"
  else
    echo NOT GETTING    git clone "git@github.com:${GH_ORG}/${repo}.git" "${GH_ORG}/${repo}" '----------'
  fi
done


