#!/bin/bash -e

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }

if [[ $# > 0 ]]; then
  SUB_SHELP="$1"
  shift

  if [[ -f "${script_dir}/shelps/${SUB_SHELP}" ]]; then
    cat "${script_dir}/shelps/${SUB_SHELP}" | glow
    exit 0
  else
    die "Cannot find shelp for \"$SUB_SHELP\" (Try: `ls $script_dir/shelps | tr ' ' ' ' | tr '\n' ' '`)"
  fi
fi


cat - <<'EOF'
cd leeting leeting2 leeting3 bcs bcsgh briancsparks ad redredred scratch

Notes:
https://www.slant.co/topics/1843/~best-windows-package-managers
- Windows package managers: scoop, choco, winget, nuget

PowerShell: Find-Module, Find-DscResource, Find-Script [-Repository PSGallery]

https://www.windowsremix.com/

-- Various Messages I Do Not Want to Forget -----------------------------

Win64 scikit-learn acceleration (See: https://intel.github.io/scikit-learn-intelex/)

conda install scikit-learn-intelex
python -m sklearnex my_app.py

-- ------------------------------------------------------------------

shelp         -- This command.

-- Full Usages -----------
adgit    -- Run a git command, but use creds from the active-developer user.
            Is basically an alias for 'git', but sets up the id_rsa-ad.

leetcode -- Forks codeblitzing/leetcode (from gh template) into codeblitzing/$1
            and then clones it into $1.
            -- Best to do in /d/.../leeting/codeblitzing
            -- Does NOT work in cygwin, use Git Gash

ghetem   -- Clones all of an org's or user's repos (whose name is in $1).
            They go into ./$ORG/a, ./$ORG/b, ./$ORG/c, etc.
            Hard-coded limit of 300 repos
            Stops on first failure, but...
              on second run will skip any already-done items, and...
              will skip any that caused errors.
            So, continually running it will eventually get them all clonded
              (the non-erroring ones, at least.)
         !!! cygwin only
uhpdatem -- Once you ghetem, you can gpff all of them with uhpdatem.
            Must be in the parent of ORG.
            arg[1] == ORG

-- Locations of Files -------------

Alacritty config:     %AppData%\Roaming\alacritty\alacritty.yml

-- Stuff I Always Forget ----------
conda!    -- On Windows, start anaconda navigator, start a powershell prompt.
conda info --envs
conda activate <name>
conda create <name>   # then do 'conda install m2-base' to get bash-like utils

-- Convienent Commands ------------
declare -f                  list full bash functions
declare -F                  list bash function names

git submodule init
git submodule update
git submodule update --init --recursive

# New repo for different user
git remote add origin git@github.com:activedevelopment/splat-board.git
Then, change 'github.com' to 'githubja' in the .git/config file
git config --local --add user.name "Active D Ninja"
git config --local --add user.email "activedevelopmentninja@gmail.com"
git push -u origin main

git stash push setup.py       Stash one file
git stash list
git reset --hard HEAD~1

-- Search -------------------------
List all Conan modules:     conan search -r all --raw
List all vcpkg modules:     vcpkg search
List ImageMagick fonts:     convert -list font   | egrep 'Font'

-- Docker -------------------------
docker ps
docker ps -a
docker container ls -a
docker image ls
docker volume ls
docker network ls
docker plugin ls

docker system prune --all --volumes

-- Swarm
docker service ls
docker node ls
docker stack ls
docker secret ls
docker config ls

-- BuildX
docker buildx ls

-- Snippets -----------------------
Generate SSH key:           ssh-keygen -t rsa -b 4096 -C "email.address@gmail.com" -f id_rsa-myname

-- Quick Usages -------------------
Make new leetcode repo:     leetcode      123-abc
Get all from org:           ghetem        GH_ORG_NAME
Update all from org:        uhpdatem      GH_ORG_NAME
git from AD gh user:        adgit         ...
                            wsl           --terminate (-t) <distro-name>;  --shutdown
Invoking (starting) WSL:    wsl           -u user -d distro -cd dir ('~' for HOME)
WSL info:                   wsl           -l --all/--running -v (--oneline shows available to install) (-l -v is show running status)
Static File Server          npx           http-server -p 8001 docs/_build/html/
Virtual envs                vert          [python ver num: 3.8] [env dir: venv]"

Find branch name            findbranch    name         For example, `findbranch 578`

Dump snippets files         snips

Python checkers             npx prettier  --write or --check
                            isort .       --check to only check
                            flake8        --exclude='venv/*,node_modules/*'
                            npx eslint    --max-warnings 0 --ext .js,.vue
                            black .
                            pip install   isort flake8 black

TOOD:?

change `.config/gh/config.yml` to use `ssh`, not `https`.

EOF

