#!/bin/bash -e

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
case `uname` in
  *CYGWIN*|*MINGW*|*MSYS*) script_dir=`cygpath -w ${script_dir}`
esac

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }

ensurecmd() {
  command -v $1 > /dev/null 2>&1 || die "$1 is required, but is not in PATH."
}

export GREP_COLORS='ms=01;33'
(for f in `ls ${script_dir}/snippets/`; do cat "${script_dir}/snippets/$f"; done) | egrep --color=always '^#####.*$|$'

