#!/bin/bash -e

 # For '###A' and the like, follow instructions and remove the leading space.
 ###A one-line description

 ###B longer description
 ###B
 ###B --including
 ###B --flags           And descriptions for a usage statement

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }
ensurecmd() { command -v $1 > /dev/null 2>&1 || die "$1 is required, but is not in PATH."; }

usage() {
  errcho "$@"
  errcho ""
  errcho "You might also want:"
  errcho "   . <($0 alias)"
}

[[ $# > 0 ]] || usage "Need sub-command"

COMMAND="$1"
shift

if [[ -x $script_dir/src-analyze-tools/$COMMAND ]]; then
  $script_dir/src-analyze-tools/$COMMAND $@
else
  echo "Command '$COMMAND' not found"
fi


