#!/bin/bash -e

###A touch and make executable

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
source "$script_dir/inc/utils"

if [[ $1 == -f ]]; then
  FORCE="1"
  shift
fi

if [[ -f "$@" ]]; then
  EXISTS="1"
fi

mkdir -p "$(dirname $1)"
touch "$@" && chmod +x "$@"


if [[ -n $EXISTS ]]; then
  [[ -z $FORCE ]] && die "$@ already exists, no change (but was touched and +x-ed). Use -f to force."
fi


# NOTE: If interested in cygwin, et. al. put this after the determination of script_dir:
#case `uname` in
#  *CYGWIN*|*MINGW*|*MSYS*) script_dir=`cygpath -w ${script_dir}`
#esac


cat << 'EOF' >> "$@"
#!/bin/bash -e

 # For '###A' and the like, follow instructions and remove the leading space.
 ###A one-line description

 ###B longer description
 ###B
 ###B --including
 ###B --flags           And descriptions for a usage statement

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
source "$script_dir/../inc/utils"  # Adjust path as needed



EOF

