#!/bin/bash -e

die() { echo "$@"; exit 1; }

if [[ $1 == -f ]]; then
  FORCE="1"
  shift
fi

if [[ -f "$@" ]]; then
  EXISTS="1"
fi

mkdir -p "$(dirname $1)"
touch "$@" && chmod +x "$@"


if [[ -n $EXISTS ]]; then
  [[ -z $FORCE ]] && die "$@ already exists, no change."
fi

#echo "#!/bin/bash -e" >> "$@"
#echo "" >> "$@"
#echo 'script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"' >> "$@"
#echo "" >> "$@"
#echo 'errcho() { echo "$@" 1>&2; }' >> "$@"
#echo 'die() { errcho "$@"; exit 1; }' >> "$@"
#echo "" >> "$@"

cat << 'EOF' >> "$@"
#!/bin/bash -e

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
case `uname` in
  *CYGWIN*|*MINGW*|*MSYS*) script_dir=`cygpath -w ${script_dir}`
esac

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }

ensurecmd() {
  command -v $1 > /dev/null 2>&1 || die "$1 is required, but is not in PATH."
}


EOF

