#!/bin/bash -e

 # For '###A' and the like, follow instructions and remove the leading space.
 ###A one-line description

 ###B longer description
 ###B
 ###B --including
 ###B --flags           And descriptions for a usage statement

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }
ensurecmd() { command -v $1 > /dev/null 2>&1 || die "$1 is required, but is not in PATH."; }

[[ -n $DIFF_FILE ]] || die "Must specify DIFF_FILE (use \$(realpath FILE))"
#DIFF_FILE="$HOME/tlt-openwrt-diff-v5"

COUNT="$(cat $DIFF_FILE | egrep -v '^$' | cut -d' ' -f5 | sort -n | head -1)"

if [[ $1 == "sha" ]]; then
  cat $DIFF_FILE | egrep "$COUNT$" | cut -d' ' -f4 | cut -d',' -f1 | head -1
else
  cat $DIFF_FILE | egrep "$COUNT$"
fi


