#!/bin/bash -ex

scripts_dir="$(dirname "$(readlink -f "$0")")"

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
ln -s "$HOME/sc-bin/dots/_vimrc" "$HOME/.vimrc"
vim +PluginInstall +qall
