#!/bin/bash -e

###A common utility functions for rc-scripts, like ~/.bashrc, ~/.profile

# Basic utilities
errcho() { echo "$@" 1>&2; }

# Check if script is being run or sourced
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  # This file is being executed, not sourced
  errcho "This file is meant to be sourced, not executed directly."
  errcho "Use: source \"$(basename \"${BASH_SOURCE[0]}\")\" in your script."
  exit 1
fi

## Basic utilities
#die() { errcho "$@"; exit 1; }
#ensurecmd() { command -v $1 > /dev/null 2>&1 || die "$1 is required, but is not in PATH."; }
#announce() { underline=$(printf "%0.s=" $(seq 1 ${#1})); echo -e "\e[93m\n  $1\n  $underline\n\e[0m"; }

# only echo in interactive login shells
_rc_echo() {
  if [ -n "$SSH_CLIENT" ] && [ -z "$PS1" ]; then
    return
  fi

  if [ -n "$DEVBOX_PROJECT_ROOT" ]; then
    if [[ "$DEVBOX_PROJECT_ROOT" == `pwd` ]]; then
      return
    fi
  fi

  if [ -n "$BCS_NOECHO_RCFILES" ]; then
    return
  fi

  errcho "$@"
}


