#!/bin/bash -e

 # For '###A' and the like, follow instructions and remove the leading space.
 ###A one-line description

 ###B longer description
 ###B
 ###B --including
 ###B --flags           And descriptions for a usage statement

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
source "$script_dir/../inc/utils"

errcho "Finding package $1 in Nix pkgs"
#errcho ag --vimgrep --nix '@pname += +"'$1@
ag --vimgrep --nix 'pname += +"'$1


