#!/bin/bash -e

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }
ensurecmd() { command -v $1 > /dev/null 2>&1 || die "$1 is required, but is not in PATH."; }
announce() { underline=$(printf "%0.s=" $(seq 1 ${#1})); echo -e "\e[93m\n  $1\n  $underline\n\e[0m"; }

git rev-parse --is-inside-work-tree > /dev/null 2>&1 || die "Not inside a git project dir"

pj_root="$(git rev-parse --show-toplevel)"
#echo $pj_root


if [[ $1 == cmake ]]; then
  (git --work-tree="$pj_root" ls-files --full-name | egrep "CMakeLists.txt$" && git --work-tree="$pj_root" ls-files --full-name | egrep "\.cmake$")
else
  git --work-tree="$pj_root" ls-files --full-name | egrep "\.(cpp|hpp|c|h)$"
fi


