#!/bin/bash -e

# TODO: smartly do either a workstation make-and-build or a device make-and-build, which would be a manual make

if [[ -x scripts/workstation-make ]]; then
  scripts/workstation-make "$@"
fi

if [[ -x scripts/workstation-run ]]; then
  scripts/workstation-run
fi


