#!/bin/bash -e

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }

username_repo="$(git config --get remote.origin.url | cut -d : -f 2 | cut -d '.' -f 1)"
echo $username_repo

