#!/bin/bash -e

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
source "$script_dir/../inc/utils"

username_repo="$(git config --get remote.origin.url | cut -d : -f 2 | cut -d '.' -f 1)"
echo $username_repo

