#!/bin/bash -e

 # For '###A' and the like, follow instructions and remove the leading space.
 ###A one-line description

 ###B longer description
 ###B
 ###B --including
 ###B --flags           And descriptions for a usage statement

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }
ensurecmd() { command -v $1 > /dev/null 2>&1 || die "$1 is required, but is not in PATH."; }
announce() { underline=$(printf "%0.s=" $(seq 1 ${#1})); echo -e "\e[93m\n  $1\n  $underline\n\e[0m"; }

# Function to generate section numbers
generate_section_numbers() {
  local section_number="$1"
  local section_parts=()
  IFS='.' read -ra section_parts <<< "$section_number"

  local current_section=""
  for part in "${section_parts[@]}"; do
    current_section+="$part"
    echo "-c"
    echo "$current_section"
    current_section+="."
  done
}

# Check if section number is provided as an argument
if [ $# -eq 0 ]; then
  errcho "Please provide a section number as an argument."
  exit 1
fi

# Generate section numbers
generate_section_numbers "$1"
