#!/bin/bash -e

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }
ensurecmd() { command -v $1 > /dev/null 2>&1 || die "$1 is required, but is not in PATH."; }
announce() { underline=$(printf "%0.s=" $(seq 1 ${#1})); echo -e "\e[93m\n  $1\n  $underline\n\e[0m"; }

clear

ensurecmd entr

ls-dev-files cmake | entr -c -p "$script_dir/cm" &
cmake_pid=$!

ls-dev-files | entr -c -p "$script_dir/mkr" &
src_pid=$!

wait $src_pid $cmake_pid


