#!/bin/bash -e

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }
ensurecmd() { command -v $1 > /dev/null 2>&1 || die "ensurecmd: $1 is required, but is not in PATH."; }
announce() { underline=$(printf "%0.s=" $(seq 1 ${#1})); echo -e "\e[93m\n  $1\n  $underline\n\e[0m"; }

#go run -modfile="$HOME/dev/briancsparks/go-zero/go.mod" "$HOME/dev/briancsparks/go-zero/main.go" "$@"
#go run  "$HOME/dev/briancsparks/go-zero/main.go" "$@"
#go run github.com/briancsparks/go-zero "$@"



export GOZERO_PWD=`pwd`
cd "$HOME/dev/briancsparks/go-zero"
devbox run go run .



